Mon Oct 14 17:13:55 2024 - INFO  - Start environmental preparation.
Mon Oct 14 17:14:08 2024 - INFO  - End of environmental preparation!
Mon Oct 14 17:14:08 2024 - INFO  - Start testing...
Failed to restart cloud-final.service: Unit cloud-final.service not found.
Mon Oct 14 17:14:08 2024 - ERROR - cloud-final.service restart failed
Mon Oct 14 17:14:08 2024 - ERROR - ../common/common_lib.sh line 34
Unit cloud-final.service could not be found.
Mon Oct 14 17:14:14 2024 - ERROR - cloud-final.service restart failed
Mon Oct 14 17:14:14 2024 - ERROR - ../common/common_lib.sh line 37
Failed to stop cloud-final.service: Unit cloud-final.service not loaded.
Mon Oct 14 17:14:14 2024 - ERROR - cloud-final.service stop failed
Mon Oct 14 17:14:14 2024 - ERROR - ../common/common_lib.sh line 39
Unit cloud-final.service could not be found.
Mon Oct 14 17:14:20 2024 - ERROR - cloud-final.service stop failed
Mon Oct 14 17:14:20 2024 - ERROR - ../common/common_lib.sh line 42
Failed to start cloud-final.service: Unit cloud-final.service not found.
Mon Oct 14 17:14:20 2024 - ERROR - cloud-final.service start failed
Mon Oct 14 17:14:20 2024 - ERROR - ../common/common_lib.sh line 44
Unit cloud-final.service could not be found.
Mon Oct 14 17:14:26 2024 - ERROR - cloud-final.service start failed
Mon Oct 14 17:14:26 2024 - ERROR - ../common/common_lib.sh line 47
Mon Oct 14 17:14:26 2024 - INFO  - Unit is indirect, ignoring.
Failed to start cloud-final.service: Unit cloud-final.service not found.
Mon Oct 14 17:14:26 2024 - ERROR - Job type reload is not applicable for unit cloud-final.service
Mon Oct 14 17:14:26 2024 - ERROR - ../common/common_lib.sh line 91
Unit cloud-final.service could not be found.
Unit cloud-final.service could not be found.
Mon Oct 14 17:14:27 2024 - INFO  - Finish test!
Mon Oct 14 17:14:27 2024 - ERROR - failed to execute the case.
Mon Oct 14 17:14:27 2024 - INFO  - start environment cleanup.
Traceback (most recent call last):
  File "/root/Shea/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Shea/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
         ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: "Last metadata expiration check: 1:19:00 ago on Mon Oct 14 15:55:06 2024.\nDependencies resolved.\n================================================================================\n Package                        Arch        Version                Repo    Size\n================================================================================\nInstalling:\n cloud-init                     noarch      23.2.2-2.oe2309        OS     1.5 M\nInstalling dependencies:\n python3-babel                  noarch      2.12.1-1.oe2309        OS     7.3 M\n python3-blinker                noarch      1.6.2-1.oe2309         OS      36 k\n python3-chardet                noarch      5.1.0-1.oe2309         OS     282 k\n python3-charset-normalizer     noarch      3.2.0-1.oe2309         OS     101 k\n python3-configobj              noarch      5.0.6-19.oe2309        OS      82 k\n python3-importlib-metadata     noarch      6.1.0-2.oe2309         OS      54 k\n python3-jinja2                 noarch      3.1.2-2.oe2309         OS     327 k\n python3-jsonpatch              noarch      1.33-1.oe2309          OS      32 k\n python3-jsonpointer            noarch      2.4-1.oe2309           OS      21 k\n python3-jsonschema             noarch      4.0.1-1.oe2309         OS     176 k\n python3-jwt                    noarch      2.7.0-1.oe2309         OS      63 k\n python3-netifaces              riscv64     0.11.0-1.oe2309        OS      21 k\n python3-oauthlib               noarch      3.2.2-1.oe2309         OS     233 k\n python3-prettytable            noarch      3.8.0-1.oe2309         OS      69 k\n python3-pyrsistent             riscv64     0.19.3-1.oe2309        OS     130 k\n python3-pyserial               noarch      3.5-4.oe2309           OS     225 k\n python3-pysocks                noarch      1.7.1-2.oe2309         OS      40 k\n python3-requests               noarch      2.31.0-1.oe2309        OS     133 k\n python3-urllib3                noarch      1.26.16-2.oe2309       OS     254 k\n python3-wcwidth                noarch      0.2.6-1.oe2309         OS      44 k\n python3-zipp                   noarch      3.15.0-2.oe2309        OS      24 k\n\nTransaction Summary\n================================================================================\nInstall  22 Packages\n\nTotal download size: 11 M\nInstalled size: 47 M\nDownloading Packages:\n[MIRROR] python3-babel-2.12.1-1.oe2309.noarch.rpm: Curl error (6): Couldn't resolve host name for https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/repo/23.09/OS/riscv64/Packages/python3-babel-2.12.1-1.oe2309.noarch.rpm [Could not resolve host: mirror.iscas.ac.cn]\n[MIRROR] python3-blinker-1.6.2-1.oe2309.noarch.rpm: Curl error (6): Couldn't resolve host name for https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/repo/23.09/OS/riscv64/Packages/python3-blinker-1.6.2-1.oe2309.noarch.rpm [Could not resolve host: mirror.iscas.ac.cn]\n[MIRROR] cloud-init-23.2.2-2.oe2309.noarch.rpm: Curl error (6): Couldn't resolve host name for https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/repo/23.09/OS/riscv64/Packages/cloud-init-23.2.2-2.oe2309.noarch.rpm [Could not resolve host: mirror.iscas.ac.cn]\n[MIRROR] python3-babel-2.12.1-1.oe2309.noarch.rpm: Curl error (6): Couldn't resolve host name for https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/repo/23.09/OS/riscv64/Packages/python3-babel-2.12.1-1.oe2309.noarch.rpm [Could not resolve host: mirror.iscas.ac.cn]\n[MIRROR] python3-blinker-1.6.2-1.oe2309.noarch.rpm: Curl error (6): Couldn't resolve host name for https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/repo/23.09/OS/riscv64/Packages/python3-blinker-1.6.2-1.oe2309.noarch.rpm [Could not resolve host: mirror.iscas.ac.cn]\n[FAILED] python3-babel-2.12.1-1.oe2309.noarch.rpm: No more mirrors to try - All mirrors were already tried without success\n\nThe downloaded packages were saved in cache until the next successful transaction.\nYou can remove cached packages by executing 'dnf clean packages'.\nError: Error downloading packages:\n  python3-babel-2.12.1-1.oe2309.noarch: Cannot download, all mirrors were already tried without success"
Mon Oct 14 17:14:28 2024 - INFO  - Finish environment cleanup!
